--001-event.sql

-----------------------------------------------------------------------
-- agent.event
create table agent.event
( id int8 not null primary key generated by default as identity
, event_ts timestamptz not null default now()
, attempts int4 not null default 0
, vt timestamptz not null default now() -- visibility threshold
, event jsonb
);

-----------------------------------------------------------------------
-- agent.event_hist
create table if not exists agent.event_hist
( id int8 not null
, event_ts timestamptz not null default now()
, attempts int4 not null default 0
, vt timestamptz not null default now() -- visibility threshold
, event jsonb
) with (
  tsdb.hypertable,
  tsdb.partition_column='event_ts'
);