--002-user-mem.sql

-----------------------------------------------------------------------
-- agent.user_memory
create table agent.user_memory
( id int8 not null primary key generated by default as identity
, user_id text not null
, memory text not null
, created timestamptz not null default now()
, updated timestamptz
);
create index on agent.user_memory (user_id);
