-- 006-custom-rules.sql
-- stores user-defined rules that are evaluated against incoming events.
-- when an event matches a rule's criteria, a custom_rule_match event is
-- enqueued for processing by TigerAgent using the rule's action_prompt.
create table agent.custom_rules
( id             bigint primary key generated by default as identity
, name           text not null
, owner_slack_id text not null
, event_type     text not null
, criteria       text not null
, action_prompt  text not null
, criteria_examples jsonb not null default '[]'::jsonb
, enabled        boolean not null default true
, created_at     timestamptz not null default now()
);

create index on agent.custom_rules (event_type, enabled);
